spring:
    config:
        activate:
            on-profile: "qa"

build:
    version: "2.0"

cards:
    message: "Welcome to DemoBank cards related QA APIs "
    contactDetails:
        name: "Utkarsh Mishra - Developer"
        email: "m.utkarsh@general.com"
    onCallSupport:
        - (+91) 1234-657-890
        - (+91) 9876-543-210